keys:
  - &vini 2241DDE7BE678A7EB70377F43F076A144E1B7B28
  - &pi age1as3dla78r6nktttyzjhmcztgry6329r69t3frtdu80hn6hgg7p6snnnjvf
creation_rules:
  - path_regex: secrets/[^/]+\.yaml 
    key_groups:
      - pgp:
        - *vini
        age:
        - *pi
