name: Build Pi configuration

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  nixos-pi:
    name: Build nixos-pi configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install qemu-user-static for cross-compilation
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static tree
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: myriad-pi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run `nix build`
        run: nix build --system aarch64-linux
