on:
  pull_request:
  push:
    branches: [main]

jobs:
  nixos-pi:
    name: Build nixos-pi configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install qemu-user-static for cross-compilation
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static tree
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: myriad-pi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run `nix build`
        run: nix build --system aarch64-linux && tree

  sd-image:
    name: Build sd-image configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install qemu-user-static for cross-compilation
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static tree
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: myriad-pi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run `nix build`
        run: nix build --system aarch64-linux .#sd-image && tree
