name: Build SD Image

on: workflow_dispatch

jobs:
  sd-image:
    name: Build sd-image configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install qemu-user-static for cross-compilation
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static tree
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: myriad-pi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run `nix build`
        run: nix build --system aarch64-linux .#sd-image
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: result/sd-image/*.img.zst
