step-ca:
    intermediatePassword: ENC[AES256_GCM,data:1is9oMbiKc7NMPm0rnIeO3Z4mYTn,iv:iuIBqyRMMqfHkx91sbdUkb3m7plcJF4o6/nPNe33WZM=,tag:GE6FV5f/LIWgxoGqRVgGlg==,type:str]
    intermediateCaKey: ENC[AES256_GCM,data:qEi+nmjQH+za1kv2rsyAvpaepQdXaKtPFRI6oHzw8udUs+tZ6a6XmKTWBZQtq98GdGm9UW+1Mivp6teBWzT9rGBSdQGNbxyMRCbLYEHKAlrii4H1G5TxSrPHqjuAnfVLTYWfUiKQg6K8kD2k/VpRKyVaQ4DK7lzhlC2fI5RM8GKsm7VeUm25CrDKvvNuhTeJukQ/GHfzrYU66ugiziNQzllAJbTnEZ7rIhbNiAk7ELWEYBTXwpEvwLF4pEeVUmGo9QX2t1hPllmpq6bigyV3srPwPnBQNltrTX+72IG62fAEzLvr9dm40zR1CYIxvg2iwoPXYmq6pVjnUN3mTfwNayO7mywNPDrumuMeUflMWOzm5jmEX550Qv+XUOMNLQcWbYShvD9bGf1GtnEU7KgZEblURiQq4CsKrko=,iv:BPGpv8beANH5ToyGPt3oc8yRIuDh69Crsr+aI9Ic+/I=,tag:nE1jep4pEWYjdpDkIY/fhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1as3dla78r6nktttyzjhmcztgry6329r69t3frtdu80hn6hgg7p6snnnjvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMjVvVjVpMDV5TUZlZWtZ
            M2VKdDdKNHFJa1hnZjVsaGlYUlc1SkhuS3pjCldwWFYyTEJLb2pIS1lQMjNqZnd1
            MVhYb0Y0MVNPQUhsMHJoeWxvaWV4NTgKLS0tIGRMZmZuUndiUXdGRS90RmVlVDM5
            VDRWMUVpSVNqWmsxdUdZQlMwdG9taW8KNRA8pthejitpv6Zn1HtzBgZtmqOv5sQL
            /llKe6lOoc4ElI7LJejF0c+OU8vFAOWR+YY+Tyo3HsAlgkUd6Komxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T22:37:02Z"
    mac: ENC[AES256_GCM,data:ssorbOdk9Uagp8XAMNapEcDZVKolBtPiEOq17+MPWIeVkIRRAxI4Lh1nDFwpCOvCxSJ/Rr25WhQz+fQ0uLrGz9mGtZTxTRRZsz5gi4B0QiCUGO/hoqpZmT/Ttg3QQlElxFK4ualXsrU1dN0FvJznMKeBKkLbCRWS2pR/b69ckSc=,iv:aMtPp7FtZE5o0LNYHPi5necIyuDgMop4hl3bQ9vlH3c=,tag:3aAQqNTlO1+HkjFCDSIVNg==,type:str]
    pgp:
        - created_at: "2024-01-15T22:36:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DPwdqFE4beygSAQdAbYxj6KbCQ521hzi0QGC8HnXk2kpAR6pDVh7EplAY+Ckw
            lWYNFI/pvBxxM/hOIzM7PgcfWzumieRaJRVIf8g6WTyZdH07SFS65Sbv1WtBb3jD
            0l4BXVU6yzueQatKZpfQsJXkB6LtIXU0XytyrBriLzTHI5EK5AZc6m42zThoptRm
            yGDptJ9r22Tfv1pW2RfD72N7hRTBxJFUJ/QeqYjsuMCVqdmp+GA1itoyvwZ/75Fl
            =Ne/W
            -----END PGP MESSAGE-----
          fp: 2241DDE7BE678A7EB70377F43F076A144E1B7B28
    unencrypted_suffix: _unencrypted
    version: 3.8.1
